/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tilt.test;

/**
 * Some sample texts in html
 * @author desmond
 */
public class Texts 
{
    public static String[][] samples = {
    {"BREWSTER","Brewster Journal p.18",
    "<div class=\"date\">1886<br>May 6<br></div>\n<div class=\"loc"
    +"ation\">Concord, Massachusetts.</div>\n<p>A fair day, pretty"
    +" sunny, with frequent intervals\nof cloudiness, cool with ra"
    +"ther high north wind</p>\n<p>Starting at 9. A.M. I rowed dow"
    +"n river. A little\nbelow the stone bridge, two snipe hunters"
    +" asked\nto be ferried across. They had started eight Snipe\n"
    +"and killed two. After I left them they fired two\nmore shots"
    +", but I was too far away to see at\nwhat, or with what resul"
    +"t. I had only my \n32 cal. pistol, and on the way to \"Balls"
    +" Hill\"\nshot only two Red-wings of which there were\ngreat "
    +"numbers everywhere, more it seemed\nto me, than I ever saw b"
    +"efore.</p>\n<p>Landing at Ball's Hill I found a small\nmixed"
    +" flock in the Oaks along the south slope\nThere were five Cr"
    +"eepers (Mniotilta,) as many \nYellow rumps, three Palm Warbl"
    +"ers, one Pine \nWarbler, and a high Canada Flycatcher. I mad"
    +"e\na good bag in a short time and started \nto return.</p>\n"
    +"<p>On the way home I shot two Red Wings, a Blue<span class=\""
    +"soft\">-\n</span>bird, a pair of Swallows (Tachycineta) and"
    +" a Solitary\nSandpiper, the latter I started from the river\n"
    +"bank on my way down in the morning. It was\nback again in t"
    +"he same place when I returned\nbut was very shy. Finally it "
    +"alighted on the\ntopmost twig of a brush heap where I shot i"
    +"t.</p>\n<p>The meadows were very beautiful, the\ngrass alrea"
    +"dy a foot high in favored places,\nAlong the river the maple"
    +"s and alders are\ndense with foliage. The marsh marigold is\n"
    +"still in full bloom.</p>\n<p>Orioles arrived this morning. "
    +"I heard one at\n</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://biodiversitylibrary.org/pageimage/437460"
    +"28\",\"despeckleBody\": false, \"blueGreenFilter\": true}\n}\n"},
    {"HARPUR","Harpur example",
    "<table><tr><td>No 17 p.253</td></tr>\n<tr><td></td><td>The 'N"
    +"evers' of Poetry<br>\n(With the very extensive original note"
    +"s by Harpur)</td></tr>\n<tr><td>No 18</td></tr>\n<tr><td></t"
    +"d><td>No II Shakespere</td></tr>\n<tr><td></td><td>No III Mi"
    +"lton - His Epic Style</td></tr>\n<tr><td></td><td>The Famous"
    +" Night Scene from Iliad VIII\n<ul style=\"list-style:none\">"
    +"<li>a. In Homeric hexameters</li>\n<li>b. In blank verse</li"
    +">\n<li>c. In Homeric Rhyme</li>\n<li>d. Very literally</li><"
    +"/ul></td></tr>\n<tr><td></td><td>A Supernaturalised Battle P"
    +"iece from Iliad XVIII\n<ul style=\"list-style:none\"><li>a. "
    +"In Homeric hexameters</li>\n<li>b. In blank verse</li>\n<li>"
    +"c. Literally</li></ul></td></tr>\n<tr><td></td><td>A song of"
    +" David inciting to Dance</td></tr>\n<tr><td></td><td>Springt"
    +"ime Gladness</td></tr>\n<tr><td></td><td>Beauty</td></tr>\n<"
    +"tr><td>No 20</td></tr>\n<tr><td></td><td>Pieces in Verse and"
    +" Prose contributed to the Sydney Times</td></tr>\n<tr><td></"
    +"td><td>? Bard The Bird of Paradise</td><td>(Poem)</td></tr>\n"
    +"<tr><td></td><td>A Man shall be a Man yet</td><td>\"</td></"
    +"tr>\n<tr><td></td><td>Impressions of Emerson</td><td>(Prose)"
    +"</td></tr>\n<tr><td></td><td>This Southern Land of Ours</td>"
    +"<td>( Poem - not from Times,I think)</td></tr>\n<tr><td></td"
    +"><td>Poetry versus Music</td><td>( Prose)</td></tr>\n<tr><td"
    +"></td><td>The Poet's Moon</td><td>( Prose)</td></tr>\n<tr><t"
    +"d></td><td>Mary Arden</td><td>( Poem)</td></tr>\n<tr><td></t"
    +"d><td>Cora</td></tr>\n<tr><td></td><td>Notes supplied by Sal"
    +"ier 2.1.1946</td></tr></table>\n<p align=\"center\">x x x x "
    +"x x</p>\n<p align=\"right\">C.W. Salier</p>\n<p align=\"righ"
    +"t\">29 November 1945</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [15.0, 25.0], [97.0, 25.0],"
    +" [97.0, 87.0], [15.0, 87.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/00000005.jpg\"}\n}\n"},
    {"CAPUANA","Capuana example",
    "<h3>Al lettore.</h3>\n<p>Quando l’autore e l’editore di quest"
    +"i due frammenti mi\npregarono di scrivere due parole di pref"
    +"azione per la pre-\nsente ristampa destinata ai bibliofili e"
    +" ai curiosi, io fran-\ncamente dissi: che mi sarebbe parso u"
    +"na bella impertinenza\nanche il solo pensiero di voler scimm"
    +"iottare il divino Aristofane:\nsi figurassero che cosa dovea"
    +" parermi l’averlo già fatto!</p>\n<p>Ma l’autore rispose che"
    +" appunto intendeva di esser da me\nscusato presso il pubblic"
    +"o di questa sua profanazione improv-\nvisata sotto l’impulso"
    +" d'una forza irresistibile.</p>\n<p>(Oh Dio, la forza irresi"
    +"stibile anche nell’arte! Dove s’andrà\na finire con essa?)</"
    +"p>\n<p>Almeno, replicai, avreste voi accarezzato un po’ di p"
    +"iù la\nforma! Aristofane, v’insegnerebbe il nostro Franchett"
    +"i che se\nn'intende meglio di tutti noialtri, Aristofane, an"
    +"che laddo-\nve sembra più negletto lavorava di fino e limava"
    +" e rilima-\nva...</p>\n<p>Bella forza! esclamò l’autore. Ma "
    +"allora non si tratterebbe\npiù d’una profanazione: come io c"
    +"onfesso...</p>\n<p>Una osservazione che mi chiuse la bocca. "
    +"E dovrebbe, credo,\nchiuderla anche a quelli che, lette le N"
    +"uove Rane,\nne daranno un giudizio pari al mio</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [10.0, 10.0], [80.0, 10.0],"
    +" [80.0, 95.0], [10.0, 95.0] ]\n\t]\n},\n\"properties\": {\n"
    //"\t\"url\": \"http://ecdosis.net/images/frontispiece3.jpg\"\n"
    +"\t\"url\": \"http://localhost/images/frontispiece3.jpg\"}\n}\n"},
    {"DEROBERTO_V2","De Roberto V2",
    "<p align=\"center\">51</p>\n<p>re, e a don Blasco il quale gl"
    +"i diceva: «Che diavolo hai fatto?» \nrispondeva, balbettando"
    +" : «Scusate... scusate... non ci pensavo più...»</p>\n<p>Ad "
    +"un invito del principe, passarono tutti nella Galleria: il p"
    +"rincipe, il du-\nca, il conte, il marchese, il cavaliere, il"
    +" signor Marco, il giudice col notaio e i \nquattro testimoni"
    +"i presero posto alla tavola ; gli altri sederono sui di-\nva"
    +"ni tutt' intorno : la principessa appartata in un angolo; do"
    +"nna Fer-\ndinanda con Chiara e la cugina Graziella da una pa"
    +"rte; Lu-\ncrezia con la duchessa e la contessa Matilde da un"
    +"' altra : il Prio-\nre, seduto sopra uno sgabello, incrociò "
    +"le mani in grembo e \nalzò gli sguardi al soffitto con un ar"
    +"ia di rassegnata indifferenza; \ndon Blasco, appoggiato in p"
    +"iedi allo stipite della finestra centra-\nle, dominava l'adu"
    +"nanza come uno spettatore diffidente dinan-\nzi a una prova "
    +"di prestigio.</p>\n<p>– «Vostra Eccellenza permette?» domand"
    +"ò il notaio, e ad un gesto \nd' assenso del principe cavò da"
    +"lla cartella un plico sul quale tut-\nti gli occhi si fermar"
    +"ono. Accertata l' incolumità dei suggelli, ri-\nscontrate le"
    +" firme, egli aprì la busta e ne tolse un \nquaderno di parec"
    +"chi fogli. Dopo un breve scambio di cerimonie col \ngiudice,"
    +" questi, in mezzo a un religioso silenzio, \ncominciò finalm"
    +"ente la lettura:</p>\n<p>«Io, Teresa Uzeda nata Risà, princi"
    +"pessa di Francalanza e Mi-\nrabella, vedova di Consalvo VII,"
    +" principe di Francalanza e Mira-\nbella, duca d'Oragua, cont"
    +"e della Venerata e di Lumera, ba-\nrone della Motta Reale, G"
    +"ibilfemi ed Alcamuro, signore delle \nterre di Bugliarello, "
    +"Malfermo, Sartorana e Caltasipala, came-\nriere di Sua Maest"
    +"à il Re (che Dio sempre feliciti).</p>\n<p>« In questo giorn"
    +"o 19 di marso dell'anno di grazia 1854, senten-\ndomi sana d"
    +"i mente ma non di corpo, raccomando l'anima mia a \nNostro S"
    +"ignore Gesù Cristo, alla Beata Vergine Maria ed a tutti i gl"
    +"orio-\nsi Santi del Paradiso e dispongo quanto segue.</p>\n<"
    +"p>«I miei amati figli non ignorano che nel giorno in cui ent"
    +"rai in \ncasa Francalanza ed assunsi l'amministrazione del p"
    +"atrimonio, \ntali e tante passività obera-</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    //"\t\"url\": \"http://ecdosis.net/images/V2-69.jpg\"\n\t}\n}\n"},
    +"\t\"url\": \"http://localhost/images/V2-69.jpg\"\n\t}\n}\n"},
    {"DEROBERTO_1920", "De Roberto 1920 edition",
    "<p align=\"center\">– 8 –</p>\n<p>che passo, non distinguendo"
    +" nulla pel buio; ma la voce\ndella principessa Margherita li"
    +" guidò:\n<p>– «Don Mariano!... Don Giacinto!...»</p>\n<p>– «"
    +"Principessa!... Signora mia!... Com'è stato?...\nE Lucrezia?"
    +"... Consalvo?... La bambina?...»\n<p>Il principino, seduto s"
    +"opra uno sgabello, con le \ngambe penzoloni, le dondolava ri"
    +"tmicamente, guar-\ndando per aria a bocca aperta; di scosta,"
    +" in un angolo \ndi divano, Lucrezia stava ingrottata, con gl"
    +"i occhi \nasciutti.</p>\n<p>– «Ma com'è avvenuto, così a un "
    +"tratto?» insi-\nsteva don Mariano.</p>\n<p>E la principessa,"
    +" aprendo le braccia:</p>\n<p>– «Non so... non capisco... È a"
    +"rrivato Salvatore \ndal Belvedere, con un biglietto del sign"
    +"or Marco... \nLì, su quella tavola, guardate... Giacomino è "
    +"partito su-\nbito.» A bassa voce, rivolta a don Mariano, int"
    +"anto \nche l'altro leggeva il biglietto: «Lucrezia voleva an"
    +"-\ndare anche lei,» aggiunse, «suo fratello ha detto di \nno"
    +"... Che ci avrebbe fatto?»</p>\n<p>– «Confusione di più!... "
    +"Il principe ha avuto ra-\ngione...»</p>\n<p>– «Niente!» annu"
    +"nziava frattanto don Giacinto, \nfinito di leggere il biglie"
    +"tto. «Non spiega niente!... \nE hanno avvertito gli altri..."
    +" hanno dispacciato?...»</p>\n<p>– «Io non so... Baldassarre."
    +"..»</p>\n<p>– «Morire così, sola sola, senza un figlio, un p"
    +"a-\nrente!» esclamava don Mariano, non potendo darsi \npace;"
    +" ma don Giacinto:</p>\n<p>– «La colpa non è di questi qui, p"
    +"overetti!... Essi \nhanno la coscienza tranquilla.»</p>\n<p>"
    +"– «Se ci avesse voluti...» cominciò la principessa, \ntimida"
    +" mente, più piano di prima; ma poi, quasi im-\npaurita, non "
    +"finì la frase.</p>\n<p>Don Mariano tirò un sospiro doloroso "
    +"e andò a met-\ntersi vicino alla signorina.</p>\n<p>– «Pover"
    +"a Lucrezia! Che disgrazia!... Avete ra-\ngione!... Ma fatevi"
    +" animo!... Coraggio!...»</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    //"\t\"url\": \"http://ecdosis.net/images/DR_1920_008.jpg\"\n\t"
    +"\t\"url\": \"http://localhost/images/DR_1920_008.jpg\"\n\t"
    +"}\n}\n"},
    {"LONDON_LIVES", "London Lives",
    "<pre>Thomas Lawrence of Grosvenor Mews Coachman\non his Oath "
    +"saith That on Saturday last (Decr. 31.)\nDept. went to Skait"
    +"ing upon the Ice in Hyde Park\nSays that a Gentleman told De"
    +"pt. that he suspected\nhe saw a Woman lying under the Ice in"
    +" a Pond\nthere between the two Bridges, about Seven Yards\nf"
    +"rom the Shore, Says that he saw the Deced under\nthe Ice the"
    +"re and by throwing Stones broke the Ice,\nnear the place whe"
    +"re Deced lay, and then went\nto the Sign of the Fox in Knigh"
    +"tsbridge and acquaint\nthe Man who keeps the House therewith"
    +", upon which\ntwo Men belonging to Mr. Chandler went with De"
    +"pt.\ninto the Park , and after Breaking the Ice Dept.\n& the"
    +" Men with a long Pole got the Deced to the Shore\nin the Par"
    +"ish of St. Margaret Westmr. Says that\nthe Deced was dead an"
    +"d appeared to have been\nsome days in the Water, Says that h"
    +"er Clothes were\non, consisting of a Black Gown & Bonnet, Bl"
    +"ack\nStockings, Black this Shoes & a Pair of yellow Buckles\n"
    +"with a Blue & white Linnen Handkerchief a Thamble and a\nha"
    +"lf penny in her Pocket. Says that the Deced's\nface looked o"
    +"f a fresh Colour, but Dept. observed no\nMarks of violence u"
    +"pon her.</pre>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [20.0, 30.0], [90.0, 30.0"
    +"], [90.0, 73.5], [20.0, 73.5] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/londonlives.jpg\"}\n}\n"},
    {"Grenada", "Oyer p.8",
    "<p>Ferrier, Charles Buret, Louis Hypolite Ventour, Elienne Ve"
    +"ntour, Charles Roy, Joinon Roy, Antoine Roy, Michel Roy, Ben"
    +" Alexandre, George, Jean Baptiste L’Oiseau, John Brown, Inno"
    +"cent Delpeche, Sylvestre Agaye, ___Bayonne, Alexis Boisac, G"
    +"eorge Berlet, ___ Breuil, Jean Francois Besson, William Burk"
    +"e, Mederic Besson, Hypolite Bruce, Charles Bruce, Michel Chr"
    +"istophe, Edward Choupin, Ellir Choupin, L’Esprit Chrisostome"
    +", Joseph Colombert, Charles Castles, Michel Duprey, Medant D"
    +"arceuil, Jean Pierre Desgallerie, Julien Ducoin, Louis Dumay"
    +", Alexandre Dumay, Ignace Dubuisset, Modeste Deslondette, Je"
    +"an Dechamps, Eugene, John Gerror, Alexis Goffier, George Haz"
    +"ell, Francois Hureault, Jean Baptist Jacob, Jean Louis Latou"
    +"sche, Jean Louis Lataste, Lambert Laurent, Edward Latang, Je"
    +"an Francois Laurent, Charles Martin, Pierre Louis Martin, Eu"
    +"stache Marciel, Vincent Marciel, Xavier Marciel, Augustine P"
    +"aponet, John Purser, Peter Purser, Jean Louis Patience fils,"
    +" Jean Francois Nicolas Pousaque, Romain Le Roy, ___Romain, _"
    +"___Romain, Pelage St. Leux, Gabriel Saint Bernard, Louis Sai"
    +"nt Bernard, Jean Saint Bernard, Paul Saint Bernard, Pierre S"
    +"aint Bernard, Regis Niervin, Elienne Gallard alias LaBastide"
    +", Julien Mederic, Jean Marie Rogon, Louis Silvain, Hiacinthe"
    +" Jean Clitandre Cloz ier, Charles Cavallie, Germain DeSuze, "
    +"Jean Baptiste Dupre’, Philip Suberan, Pierre Martial, Joachi"
    +"m Christophe, Jean Louis Gouin, Jean Louis Collet, Modeste B"
    +"esson, St. Louis Ducoin, Edward Patience, Peto Agaye, Charle"
    +"s Genie, Choco Jolicaur, Mathias Decoteaux, Sylas Decoteaux,"
    +" Estasie, Lagiberne, Jean Baptiste Castaing, Edmund, Silvain"
    +" Trouyard, Francois Siberant, Michel Louise, Bon - Homme Sim"
    +"eran, Francois, Jean Francois Ladegonde, Paul Tocqueville, A"
    +"dou, Jean Baptiste Christopher, ____Christophifils, Andre An"
    +"toine, Jacques Christophe, Jean Jacques Complou, Louis Moicr"
    +"on, Pierre Fougery, Charles Fougery, Alexis Leheault, Vincen"
    +"t Cotton, Michel Cotton, Michel Boisson, Jean Louis Boisson,"
    +" Andre’ Serio, Pierre Bernard Fedon,</p> \n<p>Bartholomew</p"
    +">\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [8.0, 9.0], [90.0, 9.0],"
    +" [90.0, 78.0], [8.0, 78.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/oyer08.png\"}\n}\n"},
    {"SONNETS", "Harpur Sonnets",
    "<h3 align=\"center\">VII"
    +"I.</h3>\n<h3 align=\"center\">ANDREW MARVEL.</h3>\n<p>Spirit"
    +", that lookest from the starry fold<br>\nof Truth’s white ﬂo"
    +"ck, next to thy Milton there,<br>\nAccept my reverence, thou"
    +"gh feebly told!<br>\nAnd oh, my heart, from thy Example rare"
    +",<br>\nHenceforth its Being for worthiest Ends would bear!<b"
    +"r>\nThy Thoughts and Deeds were towering all and bold,<br>\n"
    +"And like the steadfast Columns that uphold<br>\nSome awful T"
    +"emple, to thy Duty were.<br>\nHow much thy story has enlarge"
    +"d my ken<br>\nOf human Greatness: Of mere Heroes, I<br>\nWit"
    +"h indignation ever read—but when<br>\nOf thee, as lifted int"
    +"o Virtue's sky,<br>\nI feel how nobly all may live and die,<"
    +"br>\nAnd glory in my brotherhood with Men.</p>\n<h3 align=\""
    +"center\">IX.</h3>\n<h3 align=\"center\">WORLDLY SUCCESS.</h3"
    +">\n<p>Worldly Prosperity is often less<br>\nA proof of havin"
    +"g than of wanting sense;<br>\nAnd most is thwarted by the no"
    +"ble excess<br>\nOf Wit, Love, Valor, or Benevolence.—<br>\nI"
    +" know a bloodless Thing at whose expense<br>\nMan ne'er rejo"
    +"iced, nor Woman; in the guess<br>\nAnd careful feel of his m"
    +"ere Selfishness<br>\nMore mathematic than a Spider;——hence,<"
    +"br>\nAlthough in Look unsightly as an Elf,<br>\nNor favoured"
    +" otherwise, and aught but clever,<br>\nNothing but Death sha"
    +"ll cut him short of pelf!<br>\nThe instinct of the Brute may"
    +" err; but never<br>\nMight even Passion from its object seve"
    +"r<br>\nA thorough Worldling's providence for Self.<br></p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/00000013.jpg\"\n,"
    +"\"hyphenated\":false\n\t}\n}\n"},
    {"Biodiversity1","First Biodiversity example",
    "May 9\nClear and cool with hig"
    +"h N. W. wind.\nA glorious day as bracing as October yet with"
    +"\nthe country wreathed in flowers.\nIn the forenoon I drove "
    +"C. to Sudbury\nThe roads are lonely and little used, after\n"
    +"passing through woodland, occasionally skirting\nbroad meado"
    +"ws. The Apple Orchards were at their\nhighest perfection wit"
    +"h patches of white. Birds were\nnumerous, but I saw nothing "
    +"of any particular\ninterest. Meadow Larks were common, one o"
    +"r\nmore being seen or heard in every meadow.\nBluebirds were"
    +" frequently seen along the road-\nside, and Orioles occurred"
    +" about the orchard\nand Elm. Shaded farmhouses in apparently"
    +" un-\ndiminished numbers. I neither saw nor heard\nany Bobol"
    +"inks, although we passed many places\nin every way suited to"
    +" their habits.\nIn the afternoon I rowed up the Assabet with"
    +"\nD. C. French. While midway of the straight reach\nabove th"
    +"e Hemlocks, my companion asked \"is that\na Yellow Warbler?\""
    +", pointing out a small bird hop-\nping about in some drift-"
    +"wood caught in the\nlower branches of the black willows lini"
    +"ng the\nwest bank. After looking at it intently for a \nmome"
    +"nt, I was amazed to recognize my old\nMt. Carmel friend, the"
    +" Prothonotary Warbler.\nWe had no gun, but it did not take l"
    +"ong to\nwhirl the boat around and start back for one.\nRetur"
    +"ning in about three quarters of an hour\nwe found our little"
    +" stranger gone, but presently\nI heard him chirp and then si"
    +"ng in an undertone\nnear at hand. At length he emerged from\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/43746022.jpg\"}\n}\n"},
    {"Zen","Tibetan Zen",
     "<p>༄། །མཁན་པོ་མ་ཧ་ཡན་གྀ་བསམ་གཏན་ཅིག་ཅར་འཇུག་པའྀ་སྒོ། འཇྀག་རྟེན་སྐྱེ་ཤི་འཁོར་བའྀ་རྩ་བ་ནི། །རྣམ་པར་<br>"
    +"རྟོག་པའྀ་སེམས་ཡྀན་ནོ། །ཅྀ་ལྟར་ཡིན་ཞེ་ན། ཐོག་མ་མྱེད་པའྀ་བག་ཆགས་ཀྱྀ་རྒྱུ་ལས་། རྣམ་པར་རྟོག་པའྀ་སེམས་<br>"
    +"གཡོས་ནས་། ཇྀ་ལྟར་གཡོས་པ་དེ་བཞིན་དུ་མཐོང་ཞིང༌། ཅི་ལྟར་མཐོང་བ་བཞིན་དུ་སྤྱད་། ཅི་ལྟར་སྤྱད་<br>"
    +"པ་བཞིན་དུ་འབྲས་བུར་འགྲུབ་པས་། དེ་བས་ན་ཡར་ཏེ་སངས་རྒྱས་མན་ཅད། མར་ཏེ་སེམས་ཅན་དམྱལ་བ་<br>"
    +"ཡན་ཅད་ཀྱང། རང་གི་རྣམ་པར་རྟོག་པ་ལས་སྤྲུལ་ཅིང་མཐོང་བར་ཟད་དེ། སེམས་མྱི་གཡོ་ན་ཆོས་རྡུལ་ཙམ་ཡང་ཐོབ་པར་</p>",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [5.0, 8.0], [95.0, 8.0],"
    +" [50.0, 45.0], [5.0, 45.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://localhost/images/tibetan-zen.jpg\"\n\t}\n}\n"}};
}
