/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tilt.test;

/**
 * Some sample texts in html
 * @author desmond
 */
public class Texts 
{
    public static String[][] samples = {
    {"HARPUR","Harpur example",
    "<table><tr><td>No 17 p.253</td></tr>\n<tr><td></td><td>The 'N"
    +"evers' of Poetry<br>\n(With the very extensive original note"
    +"s by Harpur)</td></tr>\n<tr><td>No 18</td></tr>\n<tr><td></t"
    +"d><td>No II Shakespere</td></tr>\n<tr><td></td><td>No III Mi"
    +"lton - His Epic Style</td></tr>\n<tr><td></td><td>The Famous"
    +" Night Scene from Iliad VIII\n<ul style=\"list-style:none\">"
    +"<li>a. In Homeric hexameters</li>\n<li>b. In blank verse</li"
    +">\n<li>c. In Homeric Rhyme</li>\n<li>d. Very literally</li><"
    +"/ul></td></tr>\n<tr><td></td><td>A Supernaturalised Battle P"
    +"iece from Iliad XVIII\n<ul style=\"list-style:none\"><li>a. "
    +"In Homeric hexameters</li>\n<li>b. In blank verse</li>\n<li>"
    +"c. Literally</li></ul></td></tr>\n<tr><td></td><td>A song of"
    +" David inciting to Dance</td></tr>\n<tr><td></td><td>Springt"
    +"ime Gladness</td></tr>\n<tr><td></td><td>Beauty</td></tr>\n<"
    +"tr><td>No 20</td></tr>\n<tr><td></td><td>Pieces in Verse and"
    +" Prose contributed to the Sydney Times</td></tr>\n<tr><td></"
    +"td><td>? Bard The Bird of Paradise</td><td>(Poem)</td></tr>\n"
    +"<tr><td></td><td>A Man shall be a Man yet</td><td>\"</td></"
    +"tr>\n<tr><td></td><td>Impressions of Emerson</td><td>(Prose)"
    +"</td></tr>\n<tr><td></td><td>This Southern Land of Ours</td>"
    +"<td>( Poem - not from Times,I think)</td></tr>\n<tr><td></td"
    +"><td>Poetry versus Music</td><td>( Prose)</td></tr>\n<tr><td"
    +"></td><td>The Poet's Moon</td><td>( Prose)</td></tr>\n<tr><t"
    +"d></td><td>Mary Arden</td><td>( Poem)</td></tr>\n<tr><td></t"
    +"d><td>Cora</td></tr>\n<tr><td></td><td>Notes supplied by Sal"
    +"ier 2.1.1946</td></tr></table>\n<p align=\"center\">x x x x "
    +"x x</p>\n<p align=\"right\">C.W. Salier</p>\n<p align=\"righ"
    +"t\">29 November 1945</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images//00000005.jpg\"\n\t}\n}\n"},
    {"CAPUANA","Capuana example",
    "<h3>Al lettore.</h3>\n<p>Quando l’autore e l’editore di quest"
    +"i due frammenti mi\npregarono di scrivere due parole di pref"
    +"azione per la pre-\nsente ristampa destinata ai bibliofili e"
    +" ai curiosi, io fran-\ncamente dissi: che mi sarebbe parso u"
    +"na bella impertinenza\nanche il solo pensiero di voler scimm"
    +"iottare il divino Aristofane:\nsi figurassero che cosa dovea"
    +" parermi l’averlo già fatto!</p>\n<p>Ma l’autore rispose che"
    +" appunto intendeva di esser da me\nscusato presso il pubblic"
    +"o di questa sua profanazione improv-\nvisata sotto l’impulso"
    +" d'una forza irresistibile.</p>\n<p>(Oh Dio, la forza irresi"
    +"stibile anche nell’arte! Dove s’andrà\na finire con essa?)</"
    +"p>\n<p>Almeno, replicai, avreste voi accarezzato un po’ di p"
    +"iù la\nforma! Aristofane, v’insegnerebbe il nostro Franchett"
    +"i che se\nn'intende meglio di tutti noialtri, Aristofane, an"
    +"che laddo-\nve sembra più negletto lavorava di fino e limava"
    +" e rilima-\nva...</p>\n<p>Bella forza! esclamò l’autore. Ma "
    +"allora non si tratterebbe\npiù d’una profanazione: come io c"
    +"onfesso...</p>\n<p>Una osservazione che mi chiuse la bocca. "
    +"E dovrebbe, credo,\nchiuderla anche a quelli che, lette le N"
    +"uove Rane,\nne daranno un giudizio pari al mio</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/frontispiece3.jpg\"\n"
    +"\t}\n}\n"},
    {"DEROBERTO_V2","De Roberto V2",
    "<p align=\"center\">51</p>\n<p>re, e a don Blasco il quale gl"
    +"i diceva: «Che diavolo hai fatto?» \nrispondeva, balbettando"
    +" : «Scusate... scusate... non ci pensavo più...»</p>\n<p>Ad "
    +"un invito del principe, passarono tutti nella Galleria: il p"
    +"rincipe, il du-\nca, il conte, il marchese, il cavaliere, il"
    +" signor Marco, il giudice col notaio e i \nquattro testimoni"
    +"i presero posto alla tavola ; gli altri sederono sui di-\nva"
    +"ni tutt' intorno : la principessa appartata in un angolo; do"
    +"nna Fer-\ndinanda con Chiara e la cugina Graziella da una pa"
    +"rte; Lu-\ncrezia con la duchessa e la contessa Matilde da un"
    +"' altra : il Prio-\nre, seduto sopra uno sgabello, incrociò "
    +"le mani in grembo e \nalzò gli sguardi al soffitto con un ar"
    +"ia di rassegnata indifferenza; \ndon Blasco, appoggiato in p"
    +"iedi allo stipite della finestra centra-\nle, dominava l'adu"
    +"nanza come uno spettatore diffidente dinan-\nzi a una prova "
    +"di prestigio.</p>\n<p>– «Vostra Eccellenza permette?» domand"
    +"ò il notaio, e ad un gesto \nd' assenso del principe cavò da"
    +"lla cartella un plico sul quale tut-\nti gli occhi si fermar"
    +"ono. Accertata l' incolumità dei suggelli, ri-\nscontrate le"
    +" firme, egli aprì la busta e ne tolse un \nquaderno di parec"
    +"chi fogli. Dopo un breve scambio di cerimonie col \ngiudice,"
    +" questi, in mezzo a un religioso silenzio, \ncominciò finalm"
    +"ente la lettura:</p>\n<p>«Io, Teresa Uzeda nata Risà, princi"
    +"pessa di Francalanza e Mi-\nrabella, vedova di Consalvo VII,"
    +" principe di Francalanza e Mira-\nbella, duca d'Oragua, cont"
    +"e della Venerata e di Lumera, ba-\nrone della Motta Reale, G"
    +"ibilfemi ed Alcamuro, signore delle \nterre di Bugliarello, "
    +"Malfermo, Sartorana e Caltasipala, came-\nriere di Sua Maest"
    +"à il Re (che Dio sempre feliciti).</p>\n<p>« In questo giorn"
    +"o 19 di marso dell'anno di grazia 1854, senten-\ndomi sana d"
    +"i mente ma non di corpo, raccomando l'anima mia a \nNostro S"
    +"ignore Gesù Cristo, alla Beata Vergine Maria ed a tutti i gl"
    +"orio-\nsi Santi del Paradiso e dispongo quanto segue.</p>\n<"
    +"p>«I miei amati figli non ignorano che nel giorno in cui ent"
    +"rai in \ncasa Francalanza ed assunsi l'amministrazione del p"
    +"atrimonio, \ntali e tante passività obera-</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/V2-69.jpg\"\n\t}\n}\n"},
    {"DEROBERTO_1920", "De Roberto 1920 edition",
    "<!doctype HTML5>\n<html><head>\n<meta http-equiv=\"Content-Ty"
    +"pe\" content=\"text/html; charset=UTF-8\"></meta>\n<script t"
    +"ype=\"text/javascript\" src=\"http://code.jquery.com/jquery-"
    +"1.9.0.js\"></script>\n</head>\n<body>\n<p align=\"center\">–"
    +" 8 –</p>\n<p>che passo, non distinguendo nulla pel buio; ma "
    +"la voce\ndella principessa Margherita li guidò:\n<p>– «Don M"
    +"ariano!... Don Giacinto!...»</p>\n<p>– «Principessa!... Sign"
    +"ora mia!... Com'è stato?...\nE Lucrezia?... Consalvo?... La "
    +"bambina?...»\n<p>Il principino, seduto sopra uno sgabello, c"
    +"on le \ngambe penzoloni, le dondolava ritmicamente, guar-\nd"
    +"ando per aria a bocca aperta; di scosta, in un angolo \ndi d"
    +"ivano, Lucrezia stava ingrottata, con gli occhi \nasciutti.<"
    +"/p>\n<p>– «Ma com'è avvenuto, così a un tratto?» insi-\nstev"
    +"a don Mariano.</p>\n<p>E la principessa, aprendo le braccia:"
    +"</p>\n<p>– «Non so... non capisco... È arrivato Salvatore \n"
    +"dal Belvedere, con un biglietto del signor Marco... \nLì, su"
    +" quella tavola, guardate... Giacomino è partito su-\nbito.» "
    +"A bassa voce, rivolta a don Mariano, intanto \nche l'altro l"
    +"eggeva il biglietto: «Lucrezia voleva an-\ndare anche lei,» "
    +"aggiunse, «suo fratello ha detto di \nno... Che ci avrebbe f"
    +"atto?»</p>\n<p>– «Confusione di più!... Il principe ha avuto"
    +" ra-\ngione...»</p>\n<p>– «Niente!» annunziava frattanto don"
    +" Giacinto, \nfinito di leggere il biglietto. «Non spiega nie"
    +"nte!... \nE hanno avvertito gli altri... hanno dispacciato?."
    +"..»</p>\n<p>– «Io non so... Baldassarre...»</p>\n<p>– «Morir"
    +"e così, sola sola, senza un figlio, un pa-\nrente!» esclamav"
    +"a don Mariano, non potendo darsi \npace; ma don Giacinto:</p"
    +">\n<p>– «La colpa non è di questi qui, poveretti!... Essi \n"
    +"hanno la coscienza tranquilla.»</p>\n<p>– «Se ci avesse volu"
    +"ti...» cominciò la principessa, \ntimida mente, più piano di"
    +" prima; ma poi, quasi im-\npaurita, non finì la frase.</p>\n"
    +"<p>Don Mariano tirò un sospiro doloroso e andò a met-\ntersi"
    +" vicino alla signorina.</p>\n<p>– «Povera Lucrezia! Che disg"
    +"razia!... Avete ra-\ngione!... Ma fatevi animo!... Coraggio!"
    +"...»</p>\n</body>\n</html>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/DR_1920_008.jpg\"\n\t"
    +"}\n}\n"},
    {"SONNETS", "Harpur Sonnets",
    "<p align=\"center\">THOUGHTS. 9</p>\n<h3 align=\"center\">VII"
    +"I.</h3>\n<h3 align=\"center\">ANDREW MARVEL.</h3>\n<p>Spirit"
    +", that lookest from the starry fold<br>\nof Truth’s white ﬂo"
    +"ck, next to thy Milton there,<br>\nAccept my reverence, thou"
    +"gh feebly told!<br>\nAnd oh, my heart, from thy Example rare"
    +",<br>\nHenceforth its Being for worthiest Ends would bear!<b"
    +"r>\nThy Thoughts and Deeds were towering all and bold,<br>\n"
    +"And like the steadfast Columns that uphold<br>\nSome awful T"
    +"emple, to thy Duty were.<br>\nHow much thy story has enlarge"
    +"d my ken<br>\nOf human Greatness: Of mere Heroes, I<br>\nWit"
    +"h indignation ever read—but when<br>\nOf thee, as lifted int"
    +"o Virtue's sky,<br>\nI feel how nobly all may live and die,<"
    +"br>\nAnd glory in my brotherhood with Men.</p>\n<h3 align=\""
    +"center\">IX.</h3>\n<h3 align=\"center\">WORLDLY SUCCESS.</h3"
    +">\n<p>Worldly Prosperity is often less<br>\nA proof of havin"
    +"g than of wanting sense;<br>\nAnd most is thwarted by the no"
    +"ble excess<br>\nOf Wit, Love, Valor, or Benevolence.—<br>\nI"
    +" know a bloodless Thing at whose expense<br>\nMan ne'er rejo"
    +"iced, nor Woman; in the guess<br>\nAnd careful feel of his m"
    +"ere Selfishness<br>\nMore mathematic than a Spider;——hence,<"
    +"br>\nAlthough in Look unsightly as an Elf,<br>\nNor favoured"
    +" otherwise, and aught but clever,<br>\nNothing but Death shn"
    +"ll cut him short of pelf!<br>\nThe instinct of the Brute may"
    +" err; but never<br>\nMight even Passion from its object seve"
    +"r<br>\nA thorough Worldling's providence for Self.<br></p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/00000013.jpg\"\n\t"
    +"}\n}\n"}};
}
