/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tilt.test;

/**
 * Some sample texts in html
 * @author desmond
 */
public class Texts 
{
    public static String[][] samples = {
    {"HARPUR","Harpur example",
    "<table><tr><td>No 17 p.253</td></tr>\n<tr><td></td><td>The 'N"
    +"evers' of Poetry<br>\n(With the very extensive original note"
    +"s by Harpur)</td></tr>\n<tr><td>No 18</td></tr>\n<tr><td></t"
    +"d><td>No II Shakespere</td></tr>\n<tr><td></td><td>No III Mi"
    +"lton - His Epic Style</td></tr>\n<tr><td></td><td>The Famous"
    +" Night Scene from Iliad VIII\n<ul style=\"list-style:none\">"
    +"<li>a. In Homeric hexameters</li>\n<li>b. In blank verse</li"
    +">\n<li>c. In Homeric Rhyme</li>\n<li>d. Very literally</li><"
    +"/ul></td></tr>\n<tr><td></td><td>A Supernaturalised Battle P"
    +"iece from Iliad XVIII\n<ul style=\"list-style:none\"><li>a. "
    +"In Homeric hexameters</li>\n<li>b. In blank verse</li>\n<li>"
    +"c. Literally</li></ul></td></tr>\n<tr><td></td><td>A song of"
    +" David inciting to Dance</td></tr>\n<tr><td></td><td>Springt"
    +"ime Gladness</td></tr>\n<tr><td></td><td>Beauty</td></tr>\n<"
    +"tr><td>No 20</td></tr>\n<tr><td></td><td>Pieces in Verse and"
    +" Prose contributed to the Sydney Times</td></tr>\n<tr><td></"
    +"td><td>? Bard The Bird of Paradise</td><td>(Poem)</td></tr>\n"
    +"<tr><td></td><td>A Man shall be a Man yet</td><td>\"</td></"
    +"tr>\n<tr><td></td><td>Impressions of Emerson</td><td>(Prose)"
    +"</td></tr>\n<tr><td></td><td>This Southern Land of Ours</td>"
    +"<td>( Poem - not from Times,I think)</td></tr>\n<tr><td></td"
    +"><td>Poetry versus Music</td><td>( Prose)</td></tr>\n<tr><td"
    +"></td><td>The Poet's Moon</td><td>( Prose)</td></tr>\n<tr><t"
    +"d></td><td>Mary Arden</td><td>( Poem)</td></tr>\n<tr><td></t"
    +"d><td>Cora</td></tr>\n<tr><td></td><td>Notes supplied by Sal"
    +"ier 2.1.1946</td></tr></table>\n<p align=\"center\">x x x x "
    +"x x</p>\n<p align=\"right\">C.W. Salier</p>\n<p align=\"righ"
    +"t\">29 November 1945</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images//00000005.jpg\"\n\t}\n}\n"},
    {"CAPUANA","Capuana example",
    "<h3>Al lettore.</h3>\n<p>Quando l’autore e l’editore di quest"
    +"i due frammenti mi\npregarono di scrivere due parole di pref"
    +"azione per la pre-\nsente ristampa destinata ai bibliofili e"
    +" ai curiosi, io fran-\ncamente dissi: che mi sarebbe parso u"
    +"na bella impertinenza\nanche il solo pensiero di voler scimm"
    +"iottare il divino Aristofane:\nsi figurassero che cosa dovea"
    +" parermi l’averlo già fatto!</p>\n<p>Ma l’autore rispose che"
    +" appunto intendeva di esser da me\nscusato presso il pubblic"
    +"o di questa sua profanazione improv-\nvisata sotto l’impulso"
    +" d'una forza irresistibile.</p>\n<p>(Oh Dio, la forza irresi"
    +"stibile anche nell’arte! Dove s’andrà\na finire con essa?)</"
    +"p>\n<p>Almeno, replicai, avreste voi accarezzato un po’ di p"
    +"iù la\nforma! Aristofane, v’insegnerebbe il nostro Franchett"
    +"i che se\nn'intende meglio di tutti noialtri, Aristofane, an"
    +"che laddo-\nve sembra più negletto lavorava di fino e limava"
    +" e rilima-\nva...</p>\n<p>Bella forza! esclamò l’autore. Ma "
    +"allora non si tratterebbe\npiù d’una profanazione: come io c"
    +"onfesso...</p>\n<p>Una osservazione che mi chiuse la bocca. "
    +"E dovrebbe, credo,\nchiuderla anche a quelli che, lette le N"
    +"uove Rane,\nne daranno un giudizio pari al mio</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/frontispiece3.jpg\"\n"
    +"\t}\n}\n"},
    {"DEROBERTO_V2","De Roberto V2",
    "<p align=\"center\">51</p>\n<p>re, e a don Blasco il quale gl"
    +"i diceva: «Che diavolo hai fatto?» rispondeva, balbettando: "
    +"«Scusate... scusate... non ci pensavo più...»</p>\n<p>All'in"
    +"vito del principe, passarono tutti nella Galleria: il princi"
    +"pe, il duca, il conte, il\nmarchese, il cavaliere, il signor"
    +" Marco, il giudice col notaio e i quattro testimoni presero "
    +"posto alla tavola; gli altri sederono sui divani tutt'intorn"
    +"o: la principessa appartata in un angolo; donna Ferdinanda c"
    +"on Chiara e la cugina Graziella da una parte; Lucrezia con l"
    +"a duchessa e la contessa Matilde da un'altra: il Priore, sed"
    +"uto sopra uno sgabello, incrociò le mani in grembo e alzò gl"
    +"i sguardi al soffitto con moto di rassegnata indifferenza; d"
    +"on Blasco, appoggiato in piedi allo stipite della finestra c"
    +"entrale, dominava l'adunanza come uno spettatore diffidente "
    +"dinanzi a una prova di prestigio.</p>\n<p>– «Vostra Eccellen"
    +"za permette?» domandò il notaio, e ad un gesto d'assenso del"
    +" principe cavò\ndalla cartella un plico sul quale tutti gli "
    +"occhi si fermarono. Accertata l'incolumità dei suggelli, ris"
    +"contrate le firme, egli aprì la busta e ne tolse un quaderne"
    +"tto di due o tre fogli. Dopo un breve scambio di cerimonie c"
    +"ol giudice, questi, in mezzo a un religioso silenzio, cominc"
    +"iò finalmente la lettura:</p>\n<p>«Io, Teresa Uzeda nata Ris"
    +"à, principessa di Francalanza e Mirabella, vedova di Consalv"
    +"o\nVII, principe di Francalanza e Mirabella, duca d'Oragua, "
    +"conte della Venerata e\ndi Lumera, barone della Motta Reale,"
    +" Gibilfemi ed Alcamuro, signore delle terre di Bugliarello, "
    +"Malfermo, Martorana e Caltasipala, cameriere di S. M. il Re "
    +"(che Dio sempre feliciti).</p>\n<p>In questo giorno 19 di ma"
    +"rzo dell'anno di grazia 1854, sentendomi sana di\nmente ma n"
    +"on di corpo, raccomando l'anima mia a Nostro Signore Gesù Cr"
    +"isto, alla Beata Vergine Maria ed a tutti i gloriosi Santi d"
    +"el Paradiso e dispongo quanto segue:</p>\n<p>I miei amati fi"
    +"gli non ignorano che nel giorno in cui entrai in casa Franca"
    +"lanza ed assunsi l'amministrazione del patrimonio, tali e ta"
    +"nte passività obera-</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/V2-69.jpg\"\n\t}\n}\n"},
    {"DEROBERTO_1920", "De Roberto 1920 edition",
    "<body><p align=\"center\">– 8 –</p>\n<p>che passo, non disting"
    +"uendo nulla pel buio; ma la voce della principessa Margherit"
    +"a li guidò:\n<p>– «Don Mariano!... Don Giacinto!...»</p>\n<p"
    +">– «Principessa!... Signora mia!... Com'è stato?... E Lucrez"
    +"ia?... Consalvo?... La bambina?...»\n<p>Il principino, sedut"
    +"o sopra uno sgabello, con le gambe penzoloni, le dondolava r"
    +"itmicamente, guardando per aria a bocca aperta; di scosta, i"
    +"n un angolo di divano, Lucrezia stava ingrottata, con gli oc"
    +"chi asciutti.</p>\n<p>– «Ma com'è avvenuto, così a un tratto"
    +"?» insisteva don Mariano.</p>\n<p>E la principessa, aprendo "
    +"le braccia:</p>\n<p>– «Non so... non capisco... È arrivato S"
    +"alvatore dal Belvedere, con un biglietto del signor\nMarco.."
    +". Lì, su quella tavola, guardate... Giacomino è partito subi"
    +"to.» A bassa voce, rivolta a don Mariano, intanto che l'altr"
    +"o leggeva il biglietto: «Lucrezia voleva andare anche lei,» "
    +"aggiunse, «suo fratello ha detto di no... Che ci avrebbe fat"
    +"to?»</p>\n<p>– «Confusione di più!... Il principe ha avuto r"
    +"agione...»v\n<p>– «Niente!» annunziava frattanto don Giacint"
    +"o, finito di leggere il biglietto. «Non spiega\nniente!... E"
    +" hanno avvertito gli altri... hanno dispacciato?...»v\n<p>– "
    +"«Io non so... Baldassarre...»</p>\n<p>– «Morire così, sola s"
    +"ola, senza un figlio, un parente!» esclamava don Mariano, no"
    +"n potendo\ndarsi pace; ma don Giacinto:</p>\n<p>– «La colpa "
    +"non è di questi qui, poveretti!... Essi hanno la coscienza t"
    +"ranquilla.»</p>\n<p>– «Se ci avesse voluti...» cominciò la p"
    +"rincipessa, timida mente, più piano di prima; ma poi,\nquasi"
    +" impaurita, non finì la frase.</p>\n<p>Don Mariano tirò un s"
    +"ospiro doloroso e andò a mettersi vicino alla signorina.</p>"
    +"\n<p>– «Povera Lucrezia! Che disgrazia!... Avete ragione!..."
    +" Ma fatevi animo!... Coraggio!...»</p>\n",
    "{\n\"type\": \"Feature\",\n\"geometry\": {\n\t\"type\": \"Pol"
    +"ygon\",\n\t\"coordinates\": [\n\t[ [0.0, 0.0], [100.0, 0.0],"
    +" [100.0, 100.0], [0.0, 100.0] ]\n\t]\n},\n\"properties\": {\n"
    +"\t\"url\": \"http://ecdosis.net/images/DR_1920_008.jpg\"\n\t"
    +"}\n}\n"}};
}
